spring:
    application.name: retrykafka

springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true

    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /
