spring:
    application:
        name: retrykafka
    cloud:
        stream:
            kafka:
                binder:
                    configuration:
                        retries: 3
                    brokers: ${BROKER_URL:http://localhost:9092}
                    autoAddPartitions: true
                    replication-factor: 1
                    autoCreateTopics: true
                    producer-properties:
                        key:
                            serializer: org.apache.kafka.common.serialization.StringSerializer
                    deserializationExceptionHandler: logAndContinue

            bindings:
                kafkaRetryEvents-out-0:
                    destination: retry-kafka_events
                    group: retry-kafka
                    content-type: application/json

springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true

    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /
